inherits:
  - strictness_low

ignore-patterns:
  - (^|/)\..+
  - ^docs/
  - ^build/
  - test_readme.py


test-warnings: true

output-format: grouped

dodgy:
    run: true

mccabe:
    run: false

pep257:
    run: false

pep8:
    run: true
    options:
        max-line-length: 100
    disable:
        - N807

pyflakes:
    run: true

pylint:
    run: true
    options:
        max-line-length: 80
        const-rgx: "(([A-Z_][A-Z0-9_]*)|(__.*__)|log)$"
        const-hint: "(([A-Z_][A-Z0-9_]*)|(__.*__)|log)$"
        ignored-classes: pytest
    disable:
        - C0302
        - W0142
        - W0141
        - E1123
        - W1202
        - R0204
        - C1001
        - C0201
        - C0413
